# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Workmate' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Workmate

  pod 'Alamofire' #Updated on 01/03/20 (v_4.9.1)

  pod 'Alamofire-SwiftyJSON' #Updated on 01/03/20 (v_3.0.0-v_4.0.0)

  pod 'JNKeychain' #Updated on 01/03/20 (v_0.1.4)

end
