# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Workmate' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Workmate

  pod 'Alamofire' #Updated on 24/02/2020 (v_4.9.1)

  pod 'Alamofire-SwiftyJSON' #Updated on 24/02/2020 (v_3.0.0-v_4.0.0)

end
